cudnn:
  benchmark: true
gpus: [0]
workers: 4
dataset:
  dataset: cityscapes
  root: /home/eceftl7/datasets/cityscapes
  num_classes: 19
model:
  backbone: resnet101
train:
  batch_size: 8
  shuffle: true
  crop_size: 769
  start_epoch: 0
  end_epoch: 200
  optimizer: adam
  base_lr: 0.0001
  last_mult: 1.0
  momentum: 0.9
  weight_decay: 0.0001
  betas: [0.9, 0.999]
  ignore_label: 255
  resume: False
test:
  batch_size: 1
  shuffle: false
  model_path: 'trained-models/model_best_miou_51-55.pt'
  save_images: True

