cudnn:
  benchmark: True
gpus: [0]
workers: 4
dataset:
  dataset: lpcvc
  root: /home/eceftl7/datasets/lpcvc
  num_classes: 14
model:
  backbone: resnet101
train:
  batch_size: 8
  shuffle: true
  crop_size: 512
  start_epoch: 0
  end_epoch: 1
  optimizer: adam
  base_lr: 0.0001
  last_mult: 1.0
  momentum: 0.9
  weight_decay: 0.0001
  betas: [0.9, 0.999]
  ignore_label: 255
  resume: False
prune:
  prune: True
  prune_epoch: 10
  fine_tune: 10
test:
  batch_size: 1
  shuffle: false
  model_path: 'trained-models/model_best_miou_51-55.pt'
  save_images: True

